---
- name: Ensure directories are present
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    mode: "0700"
    owner: "root"
    group: "root"
  with_items:
    - "{{ stack_pack_base_dir }}"

- name: Ensure dc script is placed
  template:
    src: dc.sh.j2
    dest: "{{ stack_pack_base_dir }}/dc.sh"
    owner: "root"
    group: "root"
    mode: "0700"
