---
- name: Restart Prowlarr Docker container
  command: "{{ stack_pack_base_dir }}/dc.sh up --detach --always-recreate-deps --force-recreate {{ item.prowlarr_docker_name }}"
  with_items: "{{ prowlarr_instances }}"
  listen: restart prowlarr
