---
- name: Set role variable facts defined by outter variables for multiple instances
  set_fact:
    "{{ role_item.key }}": "{{ role_item.value }}"
  with_dict: "{{ instance }}"
  loop_control:
    loop_var: role_item

- name: common_app_setup role
  import_role:
    name: common_app_setup
  vars:
    base_dir: "{{ tautulli_base_dir }}"
    container_name: "{{ tautulli_docker_name }}"
    dirs:
      - "{{ tautulli_base_dir }}"
      - "{{ tautulli_base_dir }}/data"
    docker_repo: "{{ tautulli_docker_repo }}"
    docker_tag: "{{ tautulli_docker_tag }}"
    dockerrun_path: "{{ tautulli_base_dir }}/dockerrun"
    dockerupdate_path: "{{ tautulli_base_dir }}/dockerupdate"
    gid: "{{ arr_gid }}"
    group: "{{ arr_user_group }}"
    mode: create
    files:
      - content: "{{ lookup('template', 'docker-compose.yml.j2') }}"
        dest: "{{ tautulli_base_dir }}/docker-compose.yml"
        owner: root
        group: root
    uid: "{{ arr_uid }}"
    user: "{{ arr_user }}"
  notify: restart tautulli

- name: Ensure options are set is in section "[Preferences]" in qBittorrent.conf
  community.general.ini_file:
    path: "{{ tautulli_base_dir }}/data/config.ini"
    section: General
    option: "{{ item.key }}"
    value: "{{ item.value }}"
    mode: '0600'
  with_dict:
    http_port: "{{ tautulli_http_port }}"
    http_host: "{{ tautulli_http_host }}"
  notify: restart tautulli

# http_host