---
- name: Set role variable facts defined by outter variables for multiple instances
  set_fact:
    "{{ role_item.key }}": "{{ role_item.value }}"
  with_dict: "{{ instance }}"
  loop_control:
    loop_var: role_item
    
- name: common_app_setup role for plex_server
  import_role:
    name: common_app_setup
  vars:
    base_dir: "{{ plex_server_base_dir }}"
    container_name: "{{ plex_server_docker_name }}"
    dirs:
      - "{{ plex_server_base_dir }}"
    docker_repo: "{{ plex_server_docker_repo }}"
    docker_tag: "{{ plex_server_docker_tag }}"
    dockerrun_path: "{{ plex_server_base_dir }}/dockerrun"
    dockerupdate_path: "{{ plex_server_base_dir }}/dockerupdate"
    gid: "{{ arr_gid }}"
    group: "{{ arr_user_group }}"
    mode: create
    files:
      - content: "{{ lookup('template', 'docker-compose.yml.j2') }}"
        dest: "{{ plex_server_base_dir }}/docker-compose.yml"
        owner: root
        group: root
    uid: "{{ arr_uid }}"
    user: "{{ arr_user }}"
  notify: restart plex_server
